#!/bin/zsh

# Work in progress. 
# Replace Extension pack due to upgrade.

# Author: ekarlsson66@gmail.com
# Date: 2019-11-11
# Version: 001
 

f="Oracle_VM_VirtualBox_Extension_Pack-6.0.14.vbox-extpack"
p="/$HOME/Applications/VirtualBox.app/Contents/MacOS/ExtensionPacks"


VBoxManage extpack install $p $f --replace


exit 0
